spring:
  thymeleaf:
    prefix: classpath:/private/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  application:
    name: login-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1902/eureka
server:
  port: 1904
  servlet:
    context-path: /login
security:
  oauth2:
    client:
      client-id: all-client
      client-secret: all-client-secret